"""业务事件常量定义模块。"""

AUTH_LOGIN_SUCCEEDED = "auth_login_succeeded"
AUTH_LOGIN_FAILED = "auth_login_failed"
AUTH_LOGOUT_SUCCEEDED = "auth_logout_succeeded"
AUTH_LOGOUT_FAILED = "auth_logout_failed"
AUTH_TOKEN_REFRESH_SUCCEEDED = "auth_token_refresh_succeeded"
AUTH_TOKEN_REFRESH_FAILED = "auth_token_refresh_failed"
AUTH_BOOTSTRAP_SUPER_ADMIN_EXISTS = "auth_bootstrap_super_admin_exists"
AUTH_BOOTSTRAP_SUPER_ADMIN_CREATED = "auth_bootstrap_super_admin_created"
AUTH_BOOTSTRAP_SUPER_ADMIN_FAILED = "auth_bootstrap_super_admin_failed"
AUTH_TOKEN_USER_EXTRACT_FAILED = "auth_token_user_extract_failed"
AUTH_RESOLVE_USER_FAILED = "auth_resolve_user_failed"
AUTH_ROLE_CHECK_FAILED = "auth_role_check_failed"
AUTH_TENANT_CONTEXT_FAILED = "auth_tenant_context_failed"

USER_CREATED = "user_created"
USER_CREATE_SUCCEEDED = "user_create_succeeded"
USER_CREATE_FAILED = "user_create_failed"
USER_UPDATED = "user_updated"
USER_UPDATE_SUCCEEDED = "user_update_succeeded"
USER_UPDATE_FAILED = "user_update_failed"
USER_DELETED = "user_deleted"
USER_GET_ME_FAILED = "user_get_me_failed"

NOTICE_PARSED = "notice_parsed"
NOTICE_PUBLISHED = "notice_published"
NOTICE_CONFIRMED = "notice_confirmed"
NOTICE_REMINDED = "notice_reminded"

STUDENT_VERIFIED = "student_verified"
STUDENT_VERIFY_SUCCEEDED = "student_verify_succeeded"
STUDENT_VERIFY_FAILED = "student_verify_failed"
STUDENT_BOUND = "student_bound"

TENANT_CREATED = "tenant_created"
TENANT_UPDATED = "tenant_updated"

TASK_DISPATCHED = "task_dispatched"
TASK_COMPLETED = "task_completed"
TASK_FAILED = "task_failed"

AI_REQUEST_SENT = "ai_request_sent"
AI_RESPONSE_RECEIVED = "ai_response_received"

MESSAGE_PUSH_SUCCEEDED = "message_push_succeeded"
MESSAGE_PUSH_FAILED = "message_push_failed"

TOKEN_DECODE_FAILED = "token_decode_failed"
TOKEN_DECODE_INVALID_TYPE = "token_decode_invalid_type"
PASSWORD_HASH_FALLBACK_USED = "password_hash_fallback_used"
PASSWORD_VERIFY_FAILED = "password_verify_failed"

REQUEST_RECEIVED = "request_received"
REQUEST_COMPLETED = "request_completed"
